import React, { useEffect, useState } from "react";
import { FiPlus, FiEdit, FiCheck, FiTrash2 } from "react-icons/fi";
import TaskModal from "./TaskModal";
import ConfirmModal from "./ConfirmModal";
import {
  getUpcomingTasks,
  createTask,
  updateTask,
  deleteTask,
  completeTask,
} from "../services/taskService";

export default function UpcomingTaskPanel({ className = "" }) {
  const [tasks, setTasks] = useState([]);
  const [loading, setLoading] = useState(false);
  const [modalOpen, setModalOpen] = useState(false);
  const [editing, setEditing] = useState(null);
  const [busyId, setBusyId] = useState(null);
  const [confirmTask, setConfirmTask] = useState(null);

  const load = async () => {
    setLoading(true);
    try {
      const data = await getUpcomingTasks(4);
      setTasks(data);
    } catch (e) {
      console.error("Failed to load tasks", e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    load();
  }, []);

  const openAdd = () => {
    setEditing(null);
    setModalOpen(true);
  };

  const openEdit = (task) => {
    setEditing(task);
    setModalOpen(true);
  };

  const handleSave = async (payload) => {
    setBusyId("save");
    try {
      if (editing?.id) {
        await updateTask(editing.id, payload);
      } else {
        await createTask(payload);
      }
      setModalOpen(false);
      await load();
    } catch (e) {
      console.error("Save failed", e);
    } finally {
      setBusyId(null);
    }
  };

  const handleConfirmDelete = async () => {
    const task = confirmTask;
    if (!task) return;

    setBusyId(task.id);

    setTasks((prev) =>
      prev.map((t) => (t.id === task.id ? { ...t, _removing: true } : t))
    );

    setTimeout(async () => {
      try {
        await deleteTask(task.id);
        setTasks((prev) => prev.filter((t) => t.id !== task.id));
      } catch (e) {
        console.error("Delete failed", e);
        await load();
      } finally {
        setBusyId(null);
        setConfirmTask(null);
      }
    }, 300);
  };

  const handleDelete = (task) => setConfirmTask(task);

  const handleComplete = async (task) => {
    setBusyId(task.id);
    try {
      await completeTask(task.id);
      await load();
    } catch (e) {
      console.error("Complete failed", e);
    } finally {
      setBusyId(null);
    }
  };

  /* Empty state */
  const renderEmpty = () => (
    <div className="w-full h-40 flex flex-col items-center justify-center gap-3 text-center p-4 font-body">
      <div className="flex items-center justify-center w-16 h-16 rounded-full bg-accent-primary/20 text-accent-primary text-2xl">
        📝
      </div>
      <h4 className="text-sm font-semibold font-header text-slate-700 dark:text-slate-100">
        No upcoming tasks
      </h4>
      <p className="text-xs text-slate-500 dark:text-slate-400 max-w-xs">
        Tasks you create will appear here. Click “Add Task” to get started.
      </p>
    </div>
  );

  return (
    <div
      className={`bg-white w-full dark:bg-darkCard shadow-neo dark:shadow-dark p-4 rounded-xl ${className}`}
    >
      {/* Header */}
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between mb-4">
        <div>
          <h3 className="text-lg font-semibold font-header">Upcoming Tasks</h3>
          <p className="text-xs text-slate-500 dark:text-slate-400 font-body">
            Tasks due soon or auto-generated by the system.
          </p>
        </div>

        <button
          onClick={openAdd}
          title="Create a new task"
          className="inline-flex w-full items-center justify-center gap-2 px-3 py-2 rounded-md bg-accent-primary text-darkText shadow hover:brightness-95 transition font-body sm:w-auto sm:py-1.5"
        >
          <FiPlus />
          <span className="text-sm">Add Task</span>
        </button>
      </div>

      {/* Loading */}
      {loading && (
        <div className="text-sm text-slate-400 font-body">Loading tasks…</div>
      )}

      {/* Empty */}
      {!loading && tasks.length === 0 && renderEmpty()}

      {/* Task list */}
      <ul className="flex flex-col gap-3 font-body">
        {tasks.map((task) => {
          const due = task.dueDate ? new Date(task.dueDate) : null;
          const time = due ? due.toLocaleString() : null;
          const removing = task._removing;

          return (
            <li
              key={task.id}
              className={`
                flex flex-col gap-3 p-3 rounded-lg transition-all
                border border-transparent hover:border-accent-primary/40 hover:bg-accent-primary/5
                animate-[fadeIn_0.35s_ease-out]
                sm:flex-row sm:items-center sm:justify-between
                ${removing ? "opacity-0 scale-95 duration-300" : ""}
              `}
            >
              <div className="flex items-start gap-3">
                <div className="w-1 h-12 rounded-full bg-accent-primary/70" />

                <div>
                  <div className="flex flex-wrap items-center gap-2">
                    <div className="text-sm font-medium font-header">
                      {task.title}
                    </div>

                    {task.priority === 1 && (
                      <span className="text-xs px-2 py-0.5 rounded bg-rose-100 text-rose-600">
                        High
                      </span>
                    )}

                    {task.source === "AUTO" && (
                      <span className="text-xs px-2 py-0.5 rounded bg-slate-100 text-slate-700">
                        Auto
                      </span>
                    )}
                  </div>

                  <div className="text-xs text-slate-400">
                    {time ?? task.date ?? "No time"}
                  </div>
                </div>
              </div>

              {/* Actions */}
              <div className="flex w-full items-center justify-end gap-1 sm:w-auto">
                <button
                  onClick={() => openEdit(task)}
                  className="p-2 rounded-lg hover:bg-accent-primary/10 text-slate-500 dark:text-slate-300 transition"
                >
                  <FiEdit />
                </button>

                <button
                  onClick={() => handleComplete(task)}
                  disabled={busyId === task.id}
                  className="p-2 rounded-lg hover:bg-green-300/10 text-green-600 transition"
                >
                  <FiCheck />
                </button>

                <button
                  onClick={() => handleDelete(task)}
                  disabled={busyId === task.id}
                  className="p-2 rounded-lg hover:bg-rose-300/10 text-rose-600 transition"
                >
                  <FiTrash2 />
                </button>
              </div>
            </li>
          );
        })}
      </ul>

      {/* Modals */}
      <TaskModal
        open={modalOpen}
        initial={editing || {}}
        onClose={() => setModalOpen(false)}
        onSave={handleSave}
      />

      {confirmTask && (
        <ConfirmModal
          open
          message={`Delete task "${confirmTask.title}"? This action cannot be undone.`}
          onCancel={() => setConfirmTask(null)}
          onConfirm={handleConfirmDelete}
        />
      )}
    </div>
  );
}
